[ejs.app]
title = "Hasta Studios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Shisuiicaro/Hasta-studios-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaWebsiteURL = "https://zelthoriaismp.cloud"
mediaYouTubeURL = "https://www.tiktok.com/@_zsmp_"
mediaDiscordURL = "https://discord.gg/zsmp"

[ejs.settings]
sourceGithubLink = "https://github.com/Shisuiicaro/Hasta-studios-Launcher"
supportLink = "https://github.com/Shisuiicaro/Hasta-studios-Launcher/issues"

[ejs.welcome]
welcomeHeader = "BEM-VINDO AO ZSMP"
welcomeDescription = """
Bem-vindo ao ZSMP, onde sua aventura no Minecraft começa! Mergulhe em um mundo de possibilidades infinitas e experiências inesquecíveis no melhor servidor SMP que você pode imaginar. Junte-se à nossa vibrante comunidade de jogadores e embarque em missões épicas, construa criações incríveis e forje amizades duradouras.

Mas espera, tem mais! Para participar da diversão, basta entrar no nosso servidor do Discord para se auto-inscrever e ter acesso ao nosso reino exclusivo de emoções. Seja você um explorador experiente ou um construtor novato, o ZSMP dá as boas-vindas a jogadores de todos os níveis de habilidade.

Então, o que você está esperando? Clique em "Continuar" e deixe as aventuras começarem!
"""
